version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgres/data
  backend:
    image: kseniyapal/restorg_backend
    env_file: .env
    volumes:
      - static:/static/
      - media:/app/media/


  gateway:
    image: kseniyapal/restorg_nginx
    env_file: .env
    ports:
      - 8088:80
    volumes:
      - static:/static/
      - media:/app/media/

  frontend: 
    image: d0kshin/restorg_react
    env_file: .env
    ports:
      - 3000:3000
    volumes:
      - static:/static/
    