version: '3'

volumes:
  sqlite_data:
  static:
  media:

services:
  db:
    image: sqlite:latest
    container_name: db-sqlite
    volumes:
      - sqlite_data
  backend:
    image: kseniyapal/restorg_backend
    volumes:
      - static:/static/
      - media:/app/media/

  gateway:
    image: kseniyapal/restorg_nginx
    ports:
      - 8088:80
    volumes:
      - static:/static/
      - media:/app/media/

  frontend: 
    image: d0kshin/restorg_react
    volumes:
      - static:/static/
    