# Generated by Django 3.2.16 on 2023-10-01 15:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItemDish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование блюда')),
                ('image', models.ImageField(upload_to='images/', verbose_name='фото блюда')),
                ('weight', models.IntegerField(verbose_name='Вес в граммах')),
                ('price', models.IntegerField(verbose_name='Цена')),
            ],
        ),
        migrations.CreateModel(
            name='MenuItemDrink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование напитка')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Фото напитка')),
                ('volume', models.IntegerField(verbose_name='Объем в мл')),
                ('price', models.IntegerField(verbose_name='Цена')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Номер столика')),
                ('comment', models.CharField(blank=True, max_length=255, verbose_name='Комментарий')),
                ('status', models.CharField(choices=[('NA', 'Not Active'), ('IP', 'In Process'), ('DDS', 'The dishes are ready'), ('DDR', 'The drinks are ready')], default='NA', max_length=3, verbose_name='Статус')),
                ('menu_dishes', models.ManyToManyField(to='orders.MenuItemDish')),
                ('menu_drink', models.ManyToManyField(to='orders.MenuItemDrink')),
                ('waiter', models.ForeignKey(blank=True, null='', on_delete=django.db.models.deletion.PROTECT, related_name='waiter', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
