# Generated by Django 3.2.16 on 2023-09-30 14:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('price', models.IntegerField(verbose_name='Цена')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Номер столика')),
                ('comment', models.CharField(blank=True, max_length=255, verbose_name='Комментарий')),
                ('menu_dishes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_dishes', to='orders.menu')),
                ('menu_drink', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_drink', to='orders.menu')),
                ('waiter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='waiter', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='menu',
            name='menu_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.menuitem'),
        ),
    ]
