# Generated by Django 3.2.16 on 2023-10-03 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='menu_drink',
        ),
        migrations.AddField(
            model_name='order',
            name='menu_drinks',
            field=models.ManyToManyField(blank=True, to='orders.MenuItemDrink'),
        ),
        migrations.AlterField(
            model_name='order',
            name='menu_dishes',
            field=models.ManyToManyField(blank=True, to='orders.MenuItemDish'),
        ),
    ]
