# Generated by Django 3.2.16 on 2023-09-30 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='menu_item',
        ),
        migrations.AddField(
            model_name='menu',
            name='menu_item',
            field=models.ManyToManyField(to='orders.MenuItem'),
        ),
    ]
