# Generated by Django 3.2.16 on 2023-10-15 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20231003_1847'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='waiter',
        ),
    ]
