# Generated by Django 3.2.16 on 2023-09-30 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20230930_1720'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItemDish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование блюда')),
                ('weight', models.IntegerField(verbose_name='Вес в граммах')),
                ('price', models.IntegerField(verbose_name='Цена')),
            ],
        ),
        migrations.CreateModel(
            name='MenuItemDrink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование напитка')),
                ('volume', models.IntegerField(verbose_name='Объем в мл')),
                ('price', models.IntegerField(verbose_name='Цена')),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='menu_dishes',
        ),
        migrations.RemoveField(
            model_name='order',
            name='menu_drink',
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
        migrations.DeleteModel(
            name='MenuItem',
        ),
        migrations.AddField(
            model_name='order',
            name='menu_dishes',
            field=models.ManyToManyField(to='orders.MenuItemDish'),
        ),
        migrations.AddField(
            model_name='order',
            name='menu_drink',
            field=models.ManyToManyField(to='orders.MenuItemDrink'),
        ),
    ]
