# Generated by Django 3.2.16 on 2023-10-15 11:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0003_remove_order_waiter'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='waiter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='waiter', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='menu_dishes',
            field=models.ManyToManyField(to='orders.MenuItemDish'),
        ),
        migrations.AlterField(
            model_name='order',
            name='menu_drinks',
            field=models.ManyToManyField(to='orders.MenuItemDrink'),
        ),
    ]
