# Generated by Django 3.2.16 on 2023-10-15 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20231015_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='menu_dishes',
            field=models.ManyToManyField(to='orders.MenuItemDish'),
        ),
        migrations.AlterField(
            model_name='order',
            name='menu_drinks',
            field=models.ManyToManyField(to='orders.MenuItemDrink'),
        ),
    ]
