# Generated by Django 4.0 on 2023-10-17 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('W', 'Waiter'), ('C', 'Cook'), ('B', 'Bartender'), ('A', 'Admin')], max_length=1),
        ),
    ]
