# Generated by Django 3.2.16 on 2023-09-30 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('W', 'Waiter'), ('C', 'Cook'), ('B', 'Bartender')], max_length=1),
        ),
    ]
