# Generated by Django 4.0 on 2023-11-13 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('W', 'Waiter'), ('C', 'Cook'), ('B', 'Bartender'), ('A', 'Admin')], max_length=10),
        ),
    ]
